В обоих случаях мы получили ошибку

Только во втором сценарии файл остался неизменным

Потому что выполнение цепочки команд закончилось после первой ошибки

## Способ проверки

У этого упражнения нет проверки

Когда вы нажмёте **Завершить** - упражнение закроется